/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthAcceptInviteRouteImport } from './routes/auth.accept-invite'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthSignInRouteImport } from './routes/auth.sign-in'
import { Route as AuthSignUpRouteImport } from './routes/auth.sign-up'
import { Route as SharedTokenRouteImport } from './routes/shared.$token'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects.index'
import { Route as AuthenticatedProjectsIdRouteImport } from './routes/_authenticated/projects.$id'
import { Route as AuthenticatedReportsIdRouteImport } from './routes/_authenticated/reports.$id'
import { Route as AuthenticatedReportsNewRouteImport } from './routes/_authenticated/reports.new'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings.account'
import { Route as AuthenticatedSettingsDirectoryRouteImport } from './routes/_authenticated/settings.directory'
import { Route as AuthenticatedSettingsOrganisationRouteImport } from './routes/_authenticated/settings.organisation'
import { Route as ApiPublicResendWebhookRouteImport } from './routes/api/public/resend-webhook'
import { Route as AuthenticatedProjectsIdDirectoryRouteImport } from './routes/_authenticated/projects.$id.directory'
import { Route as AuthenticatedReportsIdDistributeRouteImport } from './routes/_authenticated/reports.$id.distribute'
import { Route as AuthenticatedReportsIdPrintRouteImport } from './routes/_authenticated/reports.$id.print'
import { Route as ApiPublicSharedReportTokenRouteImport } from './routes/api/public/shared-report.$token'
import { Route as AuthenticatedReportsIdExtractGroupRouteImport } from './routes/_authenticated/reports.$id.extract.$group'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAcceptInviteRoute = AuthAcceptInviteRouteImport.update({
  id: '/auth/accept-invite',
  path: '/auth/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedTokenRoute = SharedTokenRouteImport.update({
  id: '/shared/$token',
  path: '/shared/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIdRoute = AuthenticatedProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsIdRoute = AuthenticatedReportsIdRouteImport.update({
  id: '/reports/$id',
  path: '/reports/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsNewRoute = AuthenticatedReportsNewRouteImport.update({
  id: '/reports/new',
  path: '/reports/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/settings/account',
    path: '/settings/account',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsDirectoryRoute =
  AuthenticatedSettingsDirectoryRouteImport.update({
    id: '/settings/directory',
    path: '/settings/directory',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsOrganisationRoute =
  AuthenticatedSettingsOrganisationRouteImport.update({
    id: '/settings/organisation',
    path: '/settings/organisation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicResendWebhookRoute = ApiPublicResendWebhookRouteImport.update({
  id: '/api/public/resend-webhook',
  path: '/api/public/resend-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjectsIdDirectoryRoute =
  AuthenticatedProjectsIdDirectoryRouteImport.update({
    id: '/directory',
    path: '/directory',
    getParentRoute: () => AuthenticatedProjectsIdRoute,
  } as any)
const AuthenticatedReportsIdDistributeRoute =
  AuthenticatedReportsIdDistributeRouteImport.update({
    id: '/distribute',
    path: '/distribute',
    getParentRoute: () => AuthenticatedReportsIdRoute,
  } as any)
const AuthenticatedReportsIdPrintRoute =
  AuthenticatedReportsIdPrintRouteImport.update({
    id: '/print',
    path: '/print',
    getParentRoute: () => AuthenticatedReportsIdRoute,
  } as any)
const ApiPublicSharedReportTokenRoute =
  ApiPublicSharedReportTokenRouteImport.update({
    id: '/api/public/shared-report/$token',
    path: '/api/public/shared-report/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedReportsIdExtractGroupRoute =
  AuthenticatedReportsIdExtractGroupRouteImport.update({
    id: '/extract/$group',
    path: '/extract/$group',
    getParentRoute: () => AuthenticatedReportsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/shared/$token': typeof SharedTokenRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRouteWithChildren
  '/reports/$id': typeof AuthenticatedReportsIdRouteWithChildren
  '/reports/new': typeof AuthenticatedReportsNewRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/directory': typeof AuthenticatedSettingsDirectoryRoute
  '/settings/organisation': typeof AuthenticatedSettingsOrganisationRoute
  '/api/public/resend-webhook': typeof ApiPublicResendWebhookRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/projects/$id/directory': typeof AuthenticatedProjectsIdDirectoryRoute
  '/reports/$id/distribute': typeof AuthenticatedReportsIdDistributeRoute
  '/reports/$id/print': typeof AuthenticatedReportsIdPrintRoute
  '/api/public/shared-report/$token': typeof ApiPublicSharedReportTokenRoute
  '/reports/$id/extract/$group': typeof AuthenticatedReportsIdExtractGroupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/shared/$token': typeof SharedTokenRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRouteWithChildren
  '/reports/$id': typeof AuthenticatedReportsIdRouteWithChildren
  '/reports/new': typeof AuthenticatedReportsNewRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/directory': typeof AuthenticatedSettingsDirectoryRoute
  '/settings/organisation': typeof AuthenticatedSettingsOrganisationRoute
  '/api/public/resend-webhook': typeof ApiPublicResendWebhookRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/projects/$id/directory': typeof AuthenticatedProjectsIdDirectoryRoute
  '/reports/$id/distribute': typeof AuthenticatedReportsIdDistributeRoute
  '/reports/$id/print': typeof AuthenticatedReportsIdPrintRoute
  '/api/public/shared-report/$token': typeof ApiPublicSharedReportTokenRoute
  '/reports/$id/extract/$group': typeof AuthenticatedReportsIdExtractGroupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/shared/$token': typeof SharedTokenRoute
  '/_authenticated/projects/$id': typeof AuthenticatedProjectsIdRouteWithChildren
  '/_authenticated/reports/$id': typeof AuthenticatedReportsIdRouteWithChildren
  '/_authenticated/reports/new': typeof AuthenticatedReportsNewRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/directory': typeof AuthenticatedSettingsDirectoryRoute
  '/_authenticated/settings/organisation': typeof AuthenticatedSettingsOrganisationRoute
  '/api/public/resend-webhook': typeof ApiPublicResendWebhookRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/projects/$id/directory': typeof AuthenticatedProjectsIdDirectoryRoute
  '/_authenticated/reports/$id/distribute': typeof AuthenticatedReportsIdDistributeRoute
  '/_authenticated/reports/$id/print': typeof AuthenticatedReportsIdPrintRoute
  '/api/public/shared-report/$token': typeof ApiPublicSharedReportTokenRoute
  '/_authenticated/reports/$id/extract/$group': typeof AuthenticatedReportsIdExtractGroupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/terms'
    | '/auth/accept-invite'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/shared/$token'
    | '/projects/$id'
    | '/reports/$id'
    | '/reports/new'
    | '/settings/account'
    | '/settings/directory'
    | '/settings/organisation'
    | '/api/public/resend-webhook'
    | '/projects/'
    | '/projects/$id/directory'
    | '/reports/$id/distribute'
    | '/reports/$id/print'
    | '/api/public/shared-report/$token'
    | '/reports/$id/extract/$group'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/terms'
    | '/auth/accept-invite'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/shared/$token'
    | '/projects/$id'
    | '/reports/$id'
    | '/reports/new'
    | '/settings/account'
    | '/settings/directory'
    | '/settings/organisation'
    | '/api/public/resend-webhook'
    | '/projects'
    | '/projects/$id/directory'
    | '/reports/$id/distribute'
    | '/reports/$id/print'
    | '/api/public/shared-report/$token'
    | '/reports/$id/extract/$group'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/privacy'
    | '/terms'
    | '/auth/accept-invite'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/shared/$token'
    | '/_authenticated/projects/$id'
    | '/_authenticated/reports/$id'
    | '/_authenticated/reports/new'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/directory'
    | '/_authenticated/settings/organisation'
    | '/api/public/resend-webhook'
    | '/_authenticated/projects/'
    | '/_authenticated/projects/$id/directory'
    | '/_authenticated/reports/$id/distribute'
    | '/_authenticated/reports/$id/print'
    | '/api/public/shared-report/$token'
    | '/_authenticated/reports/$id/extract/$group'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AuthAcceptInviteRoute: typeof AuthAcceptInviteRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  SharedTokenRoute: typeof SharedTokenRoute
  ApiPublicResendWebhookRoute: typeof ApiPublicResendWebhookRoute
  ApiPublicSharedReportTokenRoute: typeof ApiPublicSharedReportTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/accept-invite': {
      id: '/auth/accept-invite'
      path: '/auth/accept-invite'
      fullPath: '/auth/accept-invite'
      preLoaderRoute: typeof AuthAcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/$token': {
      id: '/shared/$token'
      path: '/shared/$token'
      fullPath: '/shared/$token'
      preLoaderRoute: typeof SharedTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$id': {
      id: '/_authenticated/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AuthenticatedProjectsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/$id': {
      id: '/_authenticated/reports/$id'
      path: '/reports/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof AuthenticatedReportsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/new': {
      id: '/_authenticated/reports/new'
      path: '/reports/new'
      fullPath: '/reports/new'
      preLoaderRoute: typeof AuthenticatedReportsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/directory': {
      id: '/_authenticated/settings/directory'
      path: '/settings/directory'
      fullPath: '/settings/directory'
      preLoaderRoute: typeof AuthenticatedSettingsDirectoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/organisation': {
      id: '/_authenticated/settings/organisation'
      path: '/settings/organisation'
      fullPath: '/settings/organisation'
      preLoaderRoute: typeof AuthenticatedSettingsOrganisationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/resend-webhook': {
      id: '/api/public/resend-webhook'
      path: '/api/public/resend-webhook'
      fullPath: '/api/public/resend-webhook'
      preLoaderRoute: typeof ApiPublicResendWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projects/$id/directory': {
      id: '/_authenticated/projects/$id/directory'
      path: '/directory'
      fullPath: '/projects/$id/directory'
      preLoaderRoute: typeof AuthenticatedProjectsIdDirectoryRouteImport
      parentRoute: typeof AuthenticatedProjectsIdRoute
    }
    '/_authenticated/reports/$id/distribute': {
      id: '/_authenticated/reports/$id/distribute'
      path: '/distribute'
      fullPath: '/reports/$id/distribute'
      preLoaderRoute: typeof AuthenticatedReportsIdDistributeRouteImport
      parentRoute: typeof AuthenticatedReportsIdRoute
    }
    '/_authenticated/reports/$id/print': {
      id: '/_authenticated/reports/$id/print'
      path: '/print'
      fullPath: '/reports/$id/print'
      preLoaderRoute: typeof AuthenticatedReportsIdPrintRouteImport
      parentRoute: typeof AuthenticatedReportsIdRoute
    }
    '/api/public/shared-report/$token': {
      id: '/api/public/shared-report/$token'
      path: '/api/public/shared-report/$token'
      fullPath: '/api/public/shared-report/$token'
      preLoaderRoute: typeof ApiPublicSharedReportTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reports/$id/extract/$group': {
      id: '/_authenticated/reports/$id/extract/$group'
      path: '/extract/$group'
      fullPath: '/reports/$id/extract/$group'
      preLoaderRoute: typeof AuthenticatedReportsIdExtractGroupRouteImport
      parentRoute: typeof AuthenticatedReportsIdRoute
    }
  }
}

interface AuthenticatedProjectsIdRouteChildren {
  AuthenticatedProjectsIdDirectoryRoute: typeof AuthenticatedProjectsIdDirectoryRoute
}

const AuthenticatedProjectsIdRouteChildren: AuthenticatedProjectsIdRouteChildren =
  {
    AuthenticatedProjectsIdDirectoryRoute:
      AuthenticatedProjectsIdDirectoryRoute,
  }

const AuthenticatedProjectsIdRouteWithChildren =
  AuthenticatedProjectsIdRoute._addFileChildren(
    AuthenticatedProjectsIdRouteChildren,
  )

interface AuthenticatedReportsIdRouteChildren {
  AuthenticatedReportsIdDistributeRoute: typeof AuthenticatedReportsIdDistributeRoute
  AuthenticatedReportsIdPrintRoute: typeof AuthenticatedReportsIdPrintRoute
  AuthenticatedReportsIdExtractGroupRoute: typeof AuthenticatedReportsIdExtractGroupRoute
}

const AuthenticatedReportsIdRouteChildren: AuthenticatedReportsIdRouteChildren =
  {
    AuthenticatedReportsIdDistributeRoute:
      AuthenticatedReportsIdDistributeRoute,
    AuthenticatedReportsIdPrintRoute: AuthenticatedReportsIdPrintRoute,
    AuthenticatedReportsIdExtractGroupRoute:
      AuthenticatedReportsIdExtractGroupRoute,
  }

const AuthenticatedReportsIdRouteWithChildren =
  AuthenticatedReportsIdRoute._addFileChildren(
    AuthenticatedReportsIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedProjectsIdRoute: typeof AuthenticatedProjectsIdRouteWithChildren
  AuthenticatedReportsIdRoute: typeof AuthenticatedReportsIdRouteWithChildren
  AuthenticatedReportsNewRoute: typeof AuthenticatedReportsNewRoute
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsDirectoryRoute: typeof AuthenticatedSettingsDirectoryRoute
  AuthenticatedSettingsOrganisationRoute: typeof AuthenticatedSettingsOrganisationRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedProjectsIdRoute: AuthenticatedProjectsIdRouteWithChildren,
  AuthenticatedReportsIdRoute: AuthenticatedReportsIdRouteWithChildren,
  AuthenticatedReportsNewRoute: AuthenticatedReportsNewRoute,
  AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
  AuthenticatedSettingsDirectoryRoute: AuthenticatedSettingsDirectoryRoute,
  AuthenticatedSettingsOrganisationRoute:
    AuthenticatedSettingsOrganisationRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AuthAcceptInviteRoute: AuthAcceptInviteRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  SharedTokenRoute: SharedTokenRoute,
  ApiPublicResendWebhookRoute: ApiPublicResendWebhookRoute,
  ApiPublicSharedReportTokenRoute: ApiPublicSharedReportTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
