/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthAcceptInviteRouteImport } from './routes/auth.accept-invite'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthSignInRouteImport } from './routes/auth.sign-in'
import { Route as AuthenticatedProjectsIdRouteImport } from './routes/_authenticated/projects.$id'
import { Route as AuthenticatedReportsIdRouteImport } from './routes/_authenticated/reports.$id'
import { Route as AuthenticatedReportsNewRouteImport } from './routes/_authenticated/reports.new'
import { Route as AuthenticatedSettingsDirectoryRouteImport } from './routes/_authenticated/settings.directory'
import { Route as AuthenticatedSettingsOrganisationRouteImport } from './routes/_authenticated/settings.organisation'
import { Route as AuthenticatedReportsIdPrintRouteImport } from './routes/_authenticated/reports.$id.print'
import { Route as ApiPublicSharedReportTokenRouteImport } from './routes/api/public/shared-report.$token'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthAcceptInviteRoute = AuthAcceptInviteRouteImport.update({
  id: '/auth/accept-invite',
  path: '/auth/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjectsIdRoute = AuthenticatedProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsIdRoute = AuthenticatedReportsIdRouteImport.update({
  id: '/reports/$id',
  path: '/reports/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsNewRoute = AuthenticatedReportsNewRouteImport.update({
  id: '/reports/new',
  path: '/reports/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsDirectoryRoute =
  AuthenticatedSettingsDirectoryRouteImport.update({
    id: '/settings/directory',
    path: '/settings/directory',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsOrganisationRoute =
  AuthenticatedSettingsOrganisationRouteImport.update({
    id: '/settings/organisation',
    path: '/settings/organisation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsIdPrintRoute =
  AuthenticatedReportsIdPrintRouteImport.update({
    id: '/print',
    path: '/print',
    getParentRoute: () => AuthenticatedReportsIdRoute,
  } as any)
const ApiPublicSharedReportTokenRoute =
  ApiPublicSharedReportTokenRouteImport.update({
    id: '/api/public/shared-report/$token',
    path: '/api/public/shared-report/$token',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/reports/$id': typeof AuthenticatedReportsIdRouteWithChildren
  '/reports/new': typeof AuthenticatedReportsNewRoute
  '/settings/directory': typeof AuthenticatedSettingsDirectoryRoute
  '/settings/organisation': typeof AuthenticatedSettingsOrganisationRoute
  '/reports/$id/print': typeof AuthenticatedReportsIdPrintRoute
  '/api/public/shared-report/$token': typeof ApiPublicSharedReportTokenRoute
}
export interface FileRoutesByTo {
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/': typeof AuthenticatedIndexRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/reports/$id': typeof AuthenticatedReportsIdRouteWithChildren
  '/reports/new': typeof AuthenticatedReportsNewRoute
  '/settings/directory': typeof AuthenticatedSettingsDirectoryRoute
  '/settings/organisation': typeof AuthenticatedSettingsOrganisationRoute
  '/reports/$id/print': typeof AuthenticatedReportsIdPrintRoute
  '/api/public/shared-report/$token': typeof ApiPublicSharedReportTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/_authenticated/reports/$id': typeof AuthenticatedReportsIdRouteWithChildren
  '/_authenticated/reports/new': typeof AuthenticatedReportsNewRoute
  '/_authenticated/settings/directory': typeof AuthenticatedSettingsDirectoryRoute
  '/_authenticated/settings/organisation': typeof AuthenticatedSettingsOrganisationRoute
  '/_authenticated/reports/$id/print': typeof AuthenticatedReportsIdPrintRoute
  '/api/public/shared-report/$token': typeof ApiPublicSharedReportTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/accept-invite'
    | '/auth/callback'
    | '/auth/sign-in'
    | '/projects/$id'
    | '/reports/$id'
    | '/reports/new'
    | '/settings/directory'
    | '/settings/organisation'
    | '/reports/$id/print'
    | '/api/public/shared-report/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth/accept-invite'
    | '/auth/callback'
    | '/auth/sign-in'
    | '/'
    | '/projects/$id'
    | '/reports/$id'
    | '/reports/new'
    | '/settings/directory'
    | '/settings/organisation'
    | '/reports/$id/print'
    | '/api/public/shared-report/$token'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth/accept-invite'
    | '/auth/callback'
    | '/auth/sign-in'
    | '/_authenticated/'
    | '/_authenticated/projects/$id'
    | '/_authenticated/reports/$id'
    | '/_authenticated/reports/new'
    | '/_authenticated/settings/directory'
    | '/_authenticated/settings/organisation'
    | '/_authenticated/reports/$id/print'
    | '/api/public/shared-report/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthAcceptInviteRoute: typeof AuthAcceptInviteRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthSignInRoute: typeof AuthSignInRoute
  ApiPublicSharedReportTokenRoute: typeof ApiPublicSharedReportTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/accept-invite': {
      id: '/auth/accept-invite'
      path: '/auth/accept-invite'
      fullPath: '/auth/accept-invite'
      preLoaderRoute: typeof AuthAcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projects/$id': {
      id: '/_authenticated/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AuthenticatedProjectsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/$id': {
      id: '/_authenticated/reports/$id'
      path: '/reports/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof AuthenticatedReportsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/new': {
      id: '/_authenticated/reports/new'
      path: '/reports/new'
      fullPath: '/reports/new'
      preLoaderRoute: typeof AuthenticatedReportsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/directory': {
      id: '/_authenticated/settings/directory'
      path: '/settings/directory'
      fullPath: '/settings/directory'
      preLoaderRoute: typeof AuthenticatedSettingsDirectoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/organisation': {
      id: '/_authenticated/settings/organisation'
      path: '/settings/organisation'
      fullPath: '/settings/organisation'
      preLoaderRoute: typeof AuthenticatedSettingsOrganisationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/$id/print': {
      id: '/_authenticated/reports/$id/print'
      path: '/print'
      fullPath: '/reports/$id/print'
      preLoaderRoute: typeof AuthenticatedReportsIdPrintRouteImport
      parentRoute: typeof AuthenticatedReportsIdRoute
    }
    '/api/public/shared-report/$token': {
      id: '/api/public/shared-report/$token'
      path: '/api/public/shared-report/$token'
      fullPath: '/api/public/shared-report/$token'
      preLoaderRoute: typeof ApiPublicSharedReportTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedReportsIdRouteChildren {
  AuthenticatedReportsIdPrintRoute: typeof AuthenticatedReportsIdPrintRoute
}

const AuthenticatedReportsIdRouteChildren: AuthenticatedReportsIdRouteChildren =
  {
    AuthenticatedReportsIdPrintRoute: AuthenticatedReportsIdPrintRoute,
  }

const AuthenticatedReportsIdRouteWithChildren =
  AuthenticatedReportsIdRoute._addFileChildren(
    AuthenticatedReportsIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedProjectsIdRoute: typeof AuthenticatedProjectsIdRoute
  AuthenticatedReportsIdRoute: typeof AuthenticatedReportsIdRouteWithChildren
  AuthenticatedReportsNewRoute: typeof AuthenticatedReportsNewRoute
  AuthenticatedSettingsDirectoryRoute: typeof AuthenticatedSettingsDirectoryRoute
  AuthenticatedSettingsOrganisationRoute: typeof AuthenticatedSettingsOrganisationRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedProjectsIdRoute: AuthenticatedProjectsIdRoute,
  AuthenticatedReportsIdRoute: AuthenticatedReportsIdRouteWithChildren,
  AuthenticatedReportsNewRoute: AuthenticatedReportsNewRoute,
  AuthenticatedSettingsDirectoryRoute: AuthenticatedSettingsDirectoryRoute,
  AuthenticatedSettingsOrganisationRoute:
    AuthenticatedSettingsOrganisationRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthAcceptInviteRoute: AuthAcceptInviteRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthSignInRoute: AuthSignInRoute,
  ApiPublicSharedReportTokenRoute: ApiPublicSharedReportTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
